-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Balanca"
(
    "Idbalanca" uuid NOT NULL,
    "Peso" real NOT NULL,
    "Data" date NOT NULL,
    "ProdutoId" uuid NOT NULL,
    "Quantidade" integer NOT NULL,
    PRIMARY KEY ("Idbalanca")
);

CREATE TABLE IF NOT EXISTS public."HistoricoProduto"
(
    "Idhistoricopeso" uuid NOT NULL,
    "Quantidade" integer NOT NULL,
    "Produtoid" uuid NOT NULL,
    "Data" date NOT NULL,
    PRIMARY KEY ("Idhistoricopeso")
);

CREATE TABLE IF NOT EXISTS public."Produto"
(
    "Idproduto" uuid NOT NULL,
    "Nome" character varying(200) NOT NULL,
    "Marca" character varying(200),
    "Peso" real NOT NULL,
    PRIMARY KEY ("Idproduto")
);

ALTER TABLE public."Balanca"
    ADD FOREIGN KEY ("ProdutoId")
    REFERENCES public."Produto" ("Idproduto")
    NOT VALID;


ALTER TABLE public."HistoricoProduto"
    ADD FOREIGN KEY ("Produtoid")
    REFERENCES public."Produto" ("Idproduto")
    NOT VALID;

END;